#!/usr/bin/env bash
# this is an init script

file="/var/run/my_process.pid"
case "$1" in
	start)
		./manage_my_process
		echo "$!" > $file
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat $file)"
		rm $file
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat $file)"
		rm $file
		./manage_my_process
		echo "$!" > $file
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
